; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -fix-irreducible --verify-loop-info -fix-irreducible-guard-switches -S | FileCheck %s
; RUN: opt < %s -passes='fix-irreducible,verify<loops>' -fix-irreducible-guard-switches -S | FileCheck %s
; RUN: opt < %s -passes='verify<loops>,fix-irreducible,verify<loops>' -fix-irreducible-guard-switches -S | FileCheck %s


define void @do_not_generate_switch_for_branch(i1 %cond) {
; CHECK-LABEL: define void @do_not_generate_switch_for_branch(
; CHECK-SAME: i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[COND_INV:%.*]] = xor i1 [[COND]], true
; CHECK-NEXT:    br label %[[IRR_GUARD:.*]]
; CHECK:       [[LEFT:.*]]:
; CHECK-NEXT:    br label %[[IRR_GUARD]]
; CHECK:       [[RIGHT:.*]]:
; CHECK-NEXT:    br label %[[LEFT]]
; CHECK:       [[IRR_GUARD]]:
; CHECK-NEXT:    [[GUARD_RIGHT:%.*]] = phi i1 [ true, %[[LEFT]] ], [ [[COND_INV]], %[[ENTRY]] ]
; CHECK-NEXT:    br i1 [[GUARD_RIGHT]], label %[[RIGHT]], label %[[LEFT]]
;
entry:
  br i1 %cond, label %left, label %right

left:
  br label %right

right:
  br label %left
}

define void @do_not_generate_switch_for_dummy_switch(i32 %val) {
; CHECK-LABEL: define void @do_not_generate_switch_for_dummy_switch(
; CHECK-SAME: i32 [[VAL:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    switch i32 [[VAL]], label %[[ENTRY_TARGET_LEFT:.*]] [
; CHECK-NEXT:      i32 12, label %[[ENTRY_TARGET_RIGHT:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[LEFT:.*]]:
; CHECK-NEXT:    br label %[[IRR_GUARD:.*]]
; CHECK:       [[RIGHT:.*]]:
; CHECK-NEXT:    br label %[[LEFT]]
; CHECK:       [[ENTRY_TARGET_LEFT]]:
; CHECK-NEXT:    br label %[[IRR_GUARD]]
; CHECK:       [[ENTRY_TARGET_RIGHT]]:
; CHECK-NEXT:    br label %[[IRR_GUARD]]
; CHECK:       [[IRR_GUARD]]:
; CHECK-NEXT:    [[GUARD_RIGHT:%.*]] = phi i1 [ true, %[[LEFT]] ], [ false, %[[ENTRY_TARGET_LEFT]] ], [ true, %[[ENTRY_TARGET_RIGHT]] ]
; CHECK-NEXT:    br i1 [[GUARD_RIGHT]], label %[[RIGHT]], label %[[LEFT]]
;
entry:
  switch i32 %val, label %left [ i32 12, label %right ]

left:
  br label %right

right:
  br label %left
}


define void @cycle(i32 %val) {
; CHECK-LABEL: define void @cycle(
; CHECK-SAME: i32 [[VAL:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    switch i32 [[VAL]], label %[[ENTRY_TARGET_A:.*]] [
; CHECK-NEXT:      i32 0, label %[[ENTRY_TARGET_B:.*]]
; CHECK-NEXT:      i32 1, label %[[ENTRY_TARGET_C:.*]]
; CHECK-NEXT:    ]
; CHECK:       [[A:.*]]:
; CHECK-NEXT:    br label %[[B:.*]]
; CHECK:       [[B]]:
; CHECK-NEXT:    br label %[[IRR_GUARD:.*]]
; CHECK:       [[C:.*]]:
; CHECK-NEXT:    br label %[[A]]
; CHECK:       [[ENTRY_TARGET_A]]:
; CHECK-NEXT:    br label %[[IRR_GUARD]]
; CHECK:       [[ENTRY_TARGET_B]]:
; CHECK-NEXT:    br label %[[IRR_GUARD]]
; CHECK:       [[ENTRY_TARGET_C]]:
; CHECK-NEXT:    br label %[[IRR_GUARD]]
; CHECK:       [[IRR_GUARD]]:
; CHECK-NEXT:    [[MERGED_BB_IDX:%.*]] = phi i32 [ 0, %[[B]] ], [ 1, %[[ENTRY_TARGET_A]] ], [ 2, %[[ENTRY_TARGET_B]] ], [ 0, %[[ENTRY_TARGET_C]] ]
; CHECK-NEXT:    switch i32 [[MERGED_BB_IDX]], label %[[IRR_GUARD_DEFAULT:.*]] [
; CHECK-NEXT:      i32 0, label %[[C]]
; CHECK-NEXT:      i32 1, label %[[A]]
; CHECK-NEXT:      i32 2, label %[[B]]
; CHECK-NEXT:    ]
; CHECK:       [[IRR_GUARD_DEFAULT]]:
; CHECK-NEXT:    unreachable
;
entry:
  switch i32 %val, label %a [ i32 0, label %b
  i32 1, label %c
  ]
a:
  br label %b

b:
  br label %c

c:
  br label %a
}
